services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: ./server
    image: djrecommerce-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8000:8000"

  celery_worker:
    build: ./server
    image: djrecommerce-celery-worker
    command: celery -A workers worker -l info
    volumes:
      - ./server:/app
    depends_on:
      - backend
      - redis
      - rabbitmq

  event_consumer:
    build: ./server
    image: djrecommerce-event-consumer
    command: python manage.py run_notifications_consumer
    volumes:
      - ./server:/app
    depends_on:
      - rabbitmq

  frontend:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"

volumes:
  postgres_data:
