"""
This file contains all the exceptions generated by the system
its provides a custom response error for the default errors
generated by the system
"""

from rest_framework import status
from rest_framework.exceptions import APIException

from core.constants import ErrorMessages


class AuthenticationError(APIException, Exception):
    """
    AuthenticationError Exception represents an error generated during authentication
    of an account.
    """

    status_code = status.HTTP_401_UNAUTHORIZED
    detail = ErrorMessages.AuthenticationFailed

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)


class ForbiddenError(APIException):
    """
    ForbiddenError: Use this status code for problems with authorization, that is,
    the credentials are valid but they are insufficient to grant access.
    """

    status_code = status.HTTP_403_FORBIDDEN
    detail = ErrorMessages.Forbidden

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)


class NotFoundError(APIException):
    """
    NotFoundError Exception represents an error generated when a requested resource
    is not found.
    """

    status_code = status.HTTP_404_NOT_FOUND
    detail = ErrorMessages.NotFound

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)


class BadRequestError(APIException):
    """
    BadRequestError represents an error generarted when the client provides
    an invalid input.
    """

    status_code = status.HTTP_400_BAD_REQUEST
    detail = ErrorMessages.BadRequest

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)


class ServiceUnavailable(APIException):
    """
    ServiceUnavailable represents an error generarted by the server for an unexpected situation
    """

    status_code = status.HTTP_503_SERVICE_UNAVAILABLE
    detail = ErrorMessages.AuthenticationFailed

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)
