"""
This file contains all the exceptions generated by the system
its provides a custom response error for the default errors
generated by the system
"""

from rest_framework.exceptions import APIException

from adoyen.constants import AdoyenExceptions


class AuthenticationError(APIException, Exception):
    """
    AuthenticationError Exception represents an error generated during authentication
    of an account.
    """

    authenticationError = AdoyenExceptions.authentication_error()

    status_code = authenticationError.get("code")
    detail = authenticationError.get("message")
    default_code = authenticationError.get("name")

    def __init__(self, message=None):
        if message:
            self.detail = message
            super().__init__(message)

    def __str__(self):
        return str(self.detail)


class ForbiddenError(APIException):
    """
    ForbiddenError: Use this status code for problems with authorization, that is,
    the credentials are valid but they are insufficient to grant access.
    """

    forbiddenError = AdoyenExceptions.forbidden_error()

    status_code = forbiddenError.get("code")
    detail = forbiddenError.get("message")
    default_code = forbiddenError.get("name")

    def __init__(self, message=None):
        if message:
            self.detail = message

    def __str__(self):
        return str(self.detail)


class NotFoundError(APIException):
    """
    NotFoundError Exception represents an error generated when a requested resource
    is not found.
    """

    notFoundError = AdoyenExceptions.not_found_error()

    status_code = notFoundError.get("code")
    detail = notFoundError.get("message")
    default_code = notFoundError.get("name")

    def __init__(self, message=None):
        if message:
            self.detail = message

    def __str__(self):
        return str(self.detail)
    

class BadRequestError(APIException):
    """
    BadRequestError represents an error generarted when the client provides
    an invalid input.
    """

    status_code = 400
    detail = ErrorMessages.BadRequest

    def __init__(self, detail=None):
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.detail)



class ServiceUnavailable(APIException):
    """
    ServiceUnavailable represents an error generarted by the server for an unexpected situation
    """

    internalServerError = AdoyenExceptions.internal_server_error()
    status_code = internalServerError.get("code")
    detail = internalServerError.get("message")
    default_code = internalServerError.get("name")

    def __init__(self, message=None):
        if message:
            self.detail = message

    def __str__(self):
        return str(self.detail)
