# docker-compose.yml (LOCAL)
version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      ENVIRONMENT: local
      DATABASE_URL: postgres://ecommerce:ecommerce@postgres:5432/ecommerce
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://rabbitmq:5672//
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8000:8000"

  celery_worker:
    build: ./backend
    command: celery -A project worker -l info
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://ecommerce:ecommerce@postgres:5432/ecommerce
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://rabbitmq:5672//
    depends_on:
      - backend
      - redis
      - rabbitmq

  event_consumer:
    build: ./backend
    command: python manage.py run_notifications_consumer
    volumes:
      - ./backend:/app
    environment:
      CELERY_BROKER_URL: amqp://rabbitmq:5672//
    depends_on:
      - rabbitmq

  frontend:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"

volumes:
  postgres_data:
