class ErrorMessages:
    """
    This model represents all system errors every error message generated by the system
    is sourced from here
    """

    # default error messages
    AuthenticationFailed = "Invalid credentials provided."
    BadRequest = "Your client has issued a malformed or illegal request."
    NotFound = "The resource requested was not found."
    InternalError = "The server encountered an internal error and was unable to complete your request."
    Forbidden = "The server understood the request but refuses to authorize it"

    FileAlreadyStored = "This file has already been stored."


class Strings:
    Success = "Success"


class ServiceDiscovery:
    Name = "djr_ecommerce.workers"


class DBTables:
    """
    This model represents all the tables in the database
    """

    Activity = "activities"
    Account = "accounts"
    Profile = "profiles"
    Item = "items"
    Variation = "variations"
    ItemVariation = "item_variations"
    Order = "orders"
    OrderItem = "order_items"
    Address = "addresses"
    Payment = "payments"
    Coupon = "coupons"
    Refund = "refunds"
    
class AppExceptions:
    """
    This model represents all the exceptions generated bu the system as a result of errors
    that occur during processing of the input.
    """

    @classmethod
    def authentication_error(self):
        return {
            "name": "AuthenticationError",
            "code": 401,
            "message": ErrorMessages.AuthenticationFailed,
        }

    @classmethod
    def bad_request_error(self):
        return {
            "name": "BadRequestError",
            "code": 400,
            "message": ErrorMessages.BadRequest,
        }

    @classmethod
    def forbidden_error(self):
        return {
            "name": "ForbiddenError",
            "code": 403,
            "message": ErrorMessages.Forbidden,
        }

    @classmethod
    def not_found_error(self):
        return {
            "name": "NotFoundError",
            "code": 404,
            "message": ErrorMessages.NotFound,
        }

    @classmethod
    def internal_server_error(self):
        return {
            "name": "InternalServerError",
            "code": 500,
            "message": ErrorMessages.InternalError,
        }
        
EXCEPTION_TYPES = {
    400: AppExceptions.bad_request_error(),
    401: AppExceptions.authentication_error(),
    404: AppExceptions.not_found_error(),
    500: AppExceptions.internal_server_error(),
}

class EnvironmentModes:
    Development = "dev"
    Production = "prod"
    Staging = "staging"