"""
This file contains all the exceptions generated by the system
its provides a custom response error for the default errors
generated by the system
"""

from rest_framework import status
from rest_framework.exceptions import APIException

from common.constants import ErrorMessages


class AuthenticationError(APIException, Exception):
    """
    AuthenticationError Exception represents an error generated during authentication
    of an account.
    """

    status_code = status.HTTP_401_UNAUTHORIZED
    message = ErrorMessages.AuthenticationFailed
    detail = None

    def __init__(self, message=None, detail=None):
        if message:
            self.message = message
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.message)


class ForbiddenError(APIException):
    """
    ForbiddenError: Use this status code for problems with authorization, that is,
    the credentials are valid but they are insufficient to grant access.
    """

    status_code = status.HTTP_403_FORBIDDEN
    message = ErrorMessages.Forbidden
    detail = None

    def __init__(self, message=None, detail=None):
        if message:
            self.message = message
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.message)


class NotFoundError(APIException):
    """
    NotFoundError Exception represents an error generated when a requested resource
    is not found.
    """

    status_code = status.HTTP_404_NOT_FOUND
    message = ErrorMessages.NotFound
    detail = None

    def __init__(self, message=None, detail=None):
        if message:
            self.message = message
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.message)


class BadRequestError(APIException):
    """
    BadRequestError represents an error generarted when the client provides
    an invalid input.
    """

    status_code = status.HTTP_400_BAD_REQUEST
    message = ErrorMessages.BadRequest
    detail = None

    def __init__(self, message=None, detail=None):
        if message:
            self.message = message
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.message)


class ServiceUnavailable(APIException):
    """
    ServiceUnavailable represents an error generarted by the server for an unexpected situation
    """

    status_code = status.HTTP_503_SERVICE_UNAVAILABLE
    message = ErrorMessages.AuthenticationFailed
    detail = None

    def __init__(self, message=None, detail=None):
        if message:
            self.message = message
        if detail:
            self.detail = detail

    def __str__(self):
        return str(self.message)
