class ErrorMessages:
    """
    This model represents all system errors every error message generated by the system
    is sourced from here
    """

    # default error messages
    AuthenticationFailed = "Invalid credentials provided."
    BadRequest = "Your client has issued a malformed or illegal request."
    NotFound = "The resource requested was not found."
    InternalError = "The server encountered an internal error and was unable to complete your request."
    Forbidden = "The server understood the request but refuses to authorize it"

    FileAlreadyStored = "This file has already been stored."


class Strings:
    Success = "Success"


class ServiceDiscovery:
    Name = "djr_ecommerce.workers"
