# Generated by Django 6.0 on 2026-01-07 14:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('notification', 'Notification'), ('event', 'Event'), ('audit', 'Audit'), ('webhook', 'Webhook')], db_index=True, max_length=32)),
                ('type', models.CharField(db_index=True, help_text='Domain type e.g. order.completed, user.registered', max_length=128)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, help_text='Who triggered this', null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Arbitrary structured data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, help_text='Used to prevent duplicate processing', max_length=255, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'activities',
                'indexes': [models.Index(fields=['kind', 'type'], name='activities_kind_46c720_idx'), models.Index(fields=['status'], name='activities_status_3f8f9b_idx'), models.Index(fields=['occurred_at'], name='activities_occurre_fb8f1f_idx')],
            },
        ),
    ]
